language: php
php:
  - 7.2

services:
  - mysql

branches:
  only:
    - feature/tests

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install

script:
  - composer test
